DROP TABLE IF EXISTS comment;

DROP TABLE IF EXISTS category_associations;

DROP TABLE IF EXISTS blog_posts;

DROP TABLE IF EXISTS categories;

DROP TABLE IF EXISTS user_details;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS logger;